import type { Metadata } from "next";

import "./globals.css";
import { ThemeProvider } from "next-themes";
import Header from "../components/header"


export const metadata: Metadata = {
  title: "Programe",
  description: "Generated by sanket sharma",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`bg-linear-to-br from-gray-800 via-zinc-900 to-stone-800 text-white`}
      >

          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >

        {/* header */}
        <Header />
        <main className="realtive min-h-screen container mx-auto pt-40 md:pt-32">
          {/* glow */}
              <div className="pointer-event-none absolute inset-0 -z-10 overflow-hidden">
                <div className="absolute top-0 left-1/4 w-96 h-96 bg-pink-600/20 rounded-full blur-3xl"  />
                <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-orange-600/20 rounded-full blur-3xl"  />
              </div>
          <div className="relative z-10 min-h-[73vh]">
              {children} 
          </div>
          
        
       

        {/* fotter  */}
        <footer className="border-t border-gray-800/50 py-8 px-6 max-w-7xl mx-auto">
          <div className="text-sm text-gray-400">
            made with ❤️ sanket sharma
          </div>
        </footer>

        </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
